name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-check:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: secrets
    
    steps:
    - name: Pre-cleanup
      run: docker run --rm -v ${{ github.workspace }}:/workspace alpine sh -c "rm -rf /workspace/*" || true

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Set up environments
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        RELAY_USER: ${{ secrets.RELAY_USER }}
        RELAY_PASSWORD: ${{ secrets.RELAY_PASSWORD }}
        RELAY_HOST: ${{ secrets.RELAY_HOST }}
      run: |
        cat <<EOF > backend/.env
        SMTP_USER=$SMTP_USER
        SMTP_PASS=$SMTP_PASS
        JWT_SECRET=$JWT_SECRET
        EOF
        cp backend/.env backend/src/.env
        cat <<EOF > infra/mailserver.env
        RELAY_USER=$RELAY_USER
        RELAY_PASSWORD=$RELAY_PASSWORD
        RELAY_HOST=$RELAY_HOST
        EOF
        echo "VITE_API_URL=$VITE_API_URL" >> frontend/src/.env
        
    - name: Verify Build
      run: docker compose -f infra/docker-compose.yml build

  deploy:
    needs: build-check
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
    - name: Refresh Images
      run: docker compose -f infra/docker-compose.yml down --remove-orphans
    - name: Launch Deployments
      run: docker compose -f infra/docker-compose.yml up -d --build

    - name: Clean up system
      run: docker system prune -f
        
    - name: Health Check
      run: docker ps -a
