name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Set env
      run: ./dev/setenv.sh
    - name: Build
      run: docker compose -f infra/docker-compose.yml build
    - name: Container verif
      run: docker ps -a
